base_dir: data/model/280
log_level: INFO
data:
  batch_size: 1
  dataset_dir: data/PEMS-BAY/I280
  models_dir: 280_models/
  graph_pkl_filename: data/sensor_graph/adj_mx_280.pkl
  test_batch_size: 1
model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 1
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 2
  num_nodes: 13
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 64
  seq_len: 6
  use_curriculum_learning: true
train:
  base_lr: 0.01
  dropout: 0
  epoch: 34
  epochs: 100
  epsilon: 0.001
  global_step: 24375
  log_dir: data/model/280
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  model_filename: 280_models/epo34.tar
  optimizer: adam
  patience: 50
  steps:
    - 20
    - 30
    - 40
    - 50
  test_every_n_epochs: 10
